### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by LeeeYudE**

### CODE REVIEW

**Comment by LeeeYudE** [comment]
Update build.gradle

**Comment by jtakakura** [comment]
@LeeeYudE why downgrade Kotlin and Gradle version?

**Comment by LeeeYudE** [comment]
Sorry, our project version is too old, please restore the grade and kotlin version


---Original---
From: "Junji ***@***.***&gt;
Date: Fri, Mar 4, 2022 19:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jtakakura/spine_flutter] Update build.gradle (PR #7)




 
@LeeeYudE why downgrade Kotlin and Gradle version?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jtakakura** [comment]
Ok, I'll change versions to match the flutter template version in below link.

https://github.com/flutter/flutter/blob/2.10.0/packages/flutter_tools/lib/src/android/gradle_utils.dart#L30-L32

**Comment by jtakakura** [comment]
@LeeeYudE I changed gradle and android gradle plugin versions.
And I don't changed kotlin  gradle plugin version since the version in flutter template is `1.6.10`.
Can I close this PR?


https://github.com/jtakakura/spine_flutter/commit/1bf8fe68493179e96c084cb99fd06571cbc15fcc

**Comment by LeeeYudE** [comment]
请关闭 PR，谢谢



---Original---
From: "Junji ***@***.***&gt;
Date: Sat, Mar 5, 2022 12:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jtakakura/spine_flutter] Update build.gradle (PR #7)




 
@LeeeYudE I changed gradle and android gradle plugin versions.
 And I don't changed kotlin  gradle plugin version since the version in flutter template is 1.6.10.
 Can I close this PR?
 
1bf8fe6
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
